vehicle_mash.car01_definition = {
	onplace_position_adj = -0.45,
	is_boat = false,
	player_rotation = {x=0,y=90,z=0},
	collisionbox = {-0.6, -0.05, -0.6, 0.6, 1, 0.6},
	driver_attach_at = {x=3.5,y=12,z=3.5},
	passenger_attach_at = {x=3.5,y=12,z=-3.5},
	number_of_passengers = 1,
	passenger_eye_offset = {x=8, y=0, z=0},
	wield_scale = {x=1, y=1, z=1},
	visual = "mesh",
	mesh = "car.x",
	visual_size = {x=1, y=1},
	stepheight = 1.1,
	max_speed_forward = 20,
	max_speed_reverse = 10,
	accel = 2,
	braking = 4,
	turn_speed = 2,
	drop_on_destroy = "",
	recipe = {}
}
