vehicle_mash:register_car("vehicle_mash:hover_blue", {
	description = "Blue hovercraft",
	is_boat = false,
	player_attach_at = {x=-2,y=16.5,z=0},
	player_rotation = {x=0,y=90,z=0},
	onplace_position_adj = 0,
	drop_on_destroy = "",
	recipe = {},
	inventory_image = "hovercraft_blue_inv.png",
	wield_image = "hovercraft_blue_inv.png",
	wield_scale = {x=1, y=1, z=1},
	visual = "mesh",
	mesh = "hovercraft.x",
	visual_size = {x=1, y=1},
	textures = {"hovercraft_blue.png"},
	stepheight = 0.6, -- Stepheight, 0.6 = climb slabs, 1.1 = climb nodes
	max_speed_forward = 12,
	max_speed_reverse = 0,
	accel = 2.5,
	braking = 1,
	turn_speed = 2,
	collisionbox = {-0.8,0,-0.8, 0.8,1.2,0.8},
})