-- Cars Api
dofile(minetest.get_modpath("vehicle_mash").."/api.lua")

-- Cars
dofile(minetest.get_modpath("vehicle_mash").."/126r.lua")
dofile(minetest.get_modpath("vehicle_mash").."/f1.lua")
dofile(minetest.get_modpath("vehicle_mash").."/black.lua")
dofile(minetest.get_modpath("vehicle_mash").."/blue.lua")
dofile(minetest.get_modpath("vehicle_mash").."/brown.lua")
dofile(minetest.get_modpath("vehicle_mash").."/cyan.lua")
dofile(minetest.get_modpath("vehicle_mash").."/dark_green.lua")
dofile(minetest.get_modpath("vehicle_mash").."/dark_grey.lua")
dofile(minetest.get_modpath("vehicle_mash").."/green.lua")
dofile(minetest.get_modpath("vehicle_mash").."/grey.lua")
dofile(minetest.get_modpath("vehicle_mash").."/magenta.lua")
dofile(minetest.get_modpath("vehicle_mash").."/orange.lua")
dofile(minetest.get_modpath("vehicle_mash").."/pink.lua")
dofile(minetest.get_modpath("vehicle_mash").."/red.lua")
dofile(minetest.get_modpath("vehicle_mash").."/violet.lua")
dofile(minetest.get_modpath("vehicle_mash").."/white.lua")
dofile(minetest.get_modpath("vehicle_mash").."/yellow.lua")
dofile(minetest.get_modpath("vehicle_mash").."/hot_rod.lua")
dofile(minetest.get_modpath("vehicle_mash").."/nyan_ride.lua")
dofile(minetest.get_modpath("vehicle_mash").."/oerkki_bliss.lua")
dofile(minetest.get_modpath("vehicle_mash").."/road_master.lua")
dofile(minetest.get_modpath("vehicle_mash").."/mese_blue.lua")
dofile(minetest.get_modpath("vehicle_mash").."/mese_pink.lua")
dofile(minetest.get_modpath("vehicle_mash").."/mese_purple.lua")

-- Boats
dofile(minetest.get_modpath("vehicle_mash").."/boat.lua")
dofile(minetest.get_modpath("vehicle_mash").."/rowboat.lua")
