-- Cars Api
dofile(minetest.get_modpath("cars").."/api.lua")

-- Cars
dofile(minetest.get_modpath("cars").."/126r.lua")
dofile(minetest.get_modpath("cars").."/f1.lua")
dofile(minetest.get_modpath("cars").."/black.lua")
dofile(minetest.get_modpath("cars").."/blue.lua")
dofile(minetest.get_modpath("cars").."/brown.lua")
dofile(minetest.get_modpath("cars").."/cyan.lua")
dofile(minetest.get_modpath("cars").."/dark_green.lua")
dofile(minetest.get_modpath("cars").."/dark_grey.lua")
dofile(minetest.get_modpath("cars").."/green.lua")
dofile(minetest.get_modpath("cars").."/grey.lua")
dofile(minetest.get_modpath("cars").."/magenta.lua")
dofile(minetest.get_modpath("cars").."/orange.lua")
dofile(minetest.get_modpath("cars").."/pink.lua")
dofile(minetest.get_modpath("cars").."/red.lua")
dofile(minetest.get_modpath("cars").."/violet.lua")
dofile(minetest.get_modpath("cars").."/white.lua")
dofile(minetest.get_modpath("cars").."/yellow.lua")
dofile(minetest.get_modpath("cars").."/hot_rod.lua")
dofile(minetest.get_modpath("cars").."/nyan_ride.lua")
dofile(minetest.get_modpath("cars").."/oerkki_bliss.lua")
dofile(minetest.get_modpath("cars").."/road_master.lua")
dofile(minetest.get_modpath("cars").."/mese_blue.lua")
dofile(minetest.get_modpath("cars").."/mese_pink.lua")
dofile(minetest.get_modpath("cars").."/mese_purple.lua")
