vehicle_mash:register_car("vehicle_mash:mesecar_blue", {
	description = "Mesecar blue",
	is_boat = false,
	player_attach_at = {x=-2.1,y=3,z=0},
	player_rotation = {x=0,y=90,z=0},
	onplace_position_adj = 0.25,
	drop_on_destroy = "",
	recipe = {},
	inventory_image = "mesecar_car1front.png",
	wield_image = "mesecar_car1front.png",
	wield_scale = {x=1, y=1, z=1},
	visual = "cube",
	mesh = "",
	visual_size = {x=1.5, y=1.5},
	textures = { -- top base front back left right
		"mesecar_car1top.png",
		"mesecar_carbase.png",
		"mesecar_car1front.png",
		"mesecar_car1back.png",
		"mesecar_car1leftside.png",
		"mesecar_car1rightside.png",
	},
	stepheight = 0.6, -- Stepheight, 0.6 = climb slabs, 1.1 = climb nodes
	max_speed_forward = 20,
	max_speed_reverse = 10,
	accel = 2,
	braking = 4,
	turn_speed = 2,
	collisionbox = {-0.75, -0.75, -0.75, 0.75, 0.75, 0.75},
})